### ISSUE TITLE
productAndShow 注释写了作废，但是根本就还在用啊。

### ISSUE THREAD

**Issue by chenzepei** [qssq/giftanim#1]

**Comment by lozn00** [comment]
嗯，我得失误，我现在还在开发， 还在维护那我更新一下。

**Comment by lozn00** [comment]
现在在想 有一个问题 就是 需要处理一个 一直在送礼物问题比如送到了x5,新用户进来应该也是x5才好 。所以我暂时要过一会才能提交了。

**Comment by lozn00** [comment]
已更新 新版本。 支持网络礼物从自定位置开始  就是设置一个接口然后自己返回指定总数，不设置则自己维护 x1 x2 x3的记录 @chenzepei

**Comment by chenzepei** [comment]
厉害。感谢QingSuiShiQian的支持。

2017-07-03 14:51 GMT+08:00 QingSuiShiQian <notifications@github.com>:
