### ISSUE TITLE
连击时的效果感觉不太好

### ISSUE THREAD

**Issue by yylyingy** [qssq/giftanim#2]
当前项目连击时的效果是最下方的礼物有连击效果，如果上面的礼物发生连击的话，就将礼物移到下方连击，这样的效果看起来非常糟糕，因为假如有两个人或者3个人都在连击的话，那么礼物就处于不断变换位置又不断在连击中，这样的效果十分不美观

**Comment by yylyingy** [comment]
我觉得应该在显示在屏幕内的礼物连击时，不应该改变礼物位置，就让他在原地连击，屏幕外的发生连击时才将它移到屏幕内，这样会比原来的效果好很多

**Comment by lozn00** [comment]
哦 ，这个连击就有点尴尬了，不过暂时可以关闭交换位置。 解决反复交换问题。

**Comment by lozn00** [comment]
那就可以根据礼物的总数或者判断 最后一个是否连击总数==0或者比自己的连击总数还要大多少个就交换一次减少交换频率，哥们很急的话我可以弄弄，哈哈 我们公司的项目的话我暂时不管了，我觉得礼物火起来了，这是好事，哈哈 有bug调节一下就好了。

**Comment by lozn00** [comment]
已解决

**Comment by yylyingy** [comment]
@qssq 给力
