### ISSUE TITLE
是否可以取消连击，按礼物队列顺序播放，那个X1就直接取消掉

### ISSUE THREAD

**Issue by Nextweekends** [qssq/giftanim#3]

**Comment by lozn00** [comment]
自定义布局把x1的那个控件隐藏了, 顺序播放则调用setShowCount =1

**Comment by Nextweekends** [comment]
连击还是存在，连续选择一个礼物播放，不叠加 顺序播放

**Comment by lozn00** [comment]
可以的，你设置问题吧。 设置一下 最大缓存是否加入队列等待。  你说的连击到底想干嘛。额，那种连击的话是由你的userid和礼物地址控制的，你继承giftanim类复写一下方法就好。就不会唯一了。叫getKey()方法 让每次都不一样就好了。

**Comment by Nextweekends** [comment]
我的意思是假设我连续送同一个礼物3次，是陆续显示3条同一个数据，而不是一条数据X3的形式，就是不需要实现打击，无论是怎么样都是加入礼物队列，然后顺序播放，动画你的就很好

**Comment by lozn00** [comment]
我已经说了啊，getKey() 返回一个取当前时间随机数字符串 原来是根据userid+地址判断的，你改一下规则就好了 ，继承这个类。

**Comment by Nextweekends** [comment]
返回随机字符串，连送礼物的时候，礼物丢失太多，也就是基本，显示完三个，最好第二组就显示一个了，之后的就丢失去了

**Comment by lozn00** [comment]
你这需求..........

**Comment by lozn00** [comment]
那么消失动画就有问题了，因为消失动画执行的时间必须那么长。 只能马上移除了似乎

**Comment by lozn00** [comment]
那样又不好看，你说怎么办？

**Comment by lozn00** [comment]
布局隐藏动画消失也需要时间，这很尴尬了。

**Comment by lozn00** [comment]
新版本提供了 setThanQueueClearFirstAndNotAddQueue  方法你看看吧

**Comment by Nextweekends** [comment]
大神，其实就是点击相同的 和 不同的礼物同一种效果，就像默默视频送礼物的循环播放

**Comment by lozn00** [comment]
giftAnimLayout.setMustAnimHide(true);//这个本来是用来修复交叉层叠的问题的，但是这里的话只能关闭这个bug修复功能了。。我已经无能为力了 布局动画太low,我也没啥比较好的办法。
        giftAnimLayout.setAllowAcrossAnimBug(true);//如果是动画消失会随点击速度加快而产生超过的数目bug越多 慢慢的点击没毛病只会超过一个。
        giftAnimLayout.setThanQueueClearFirstAndNotAddQueue(true);

**Comment by lozn00** [comment]
@Nextweekends 那种问题还是自己写吧，这里是解决多个一起显示的，突然变成单一的礼物显示我这里无能为力了，你自己写更简单，。但是你要想隐藏动画 你得单一显示无法解决用户马上点击的问题 肯定只能排队等待正如我后面说说的，感觉你的需求有点矛盾了。

**Comment by lozn00** [comment]
其他属性动画我也不太会，你可以控制以及存在的view进行唯一消失，然后新添加的插入到原来的位置，类似我里面屏蔽的一句交叉代码得实现方法。 这样也倒是可以解决问题。但是动画嘛有个时间问题，如果送礼物速度快了好像还是没法解决 哈哈哈  速度快了 你得移除时间必须加快。

**Comment by lozn00** [comment]
默默的很牛逼吗？看了下就是2个一直在显示而已，和我的排队等待一样，

**Comment by Nextweekends** [comment]
谢谢你为我解答了这么多，简单点 其实我的情况就是 连续点随机每次都不一样的情况

**Comment by lozn00** [comment]
你可以继承GiftLayout然后复写onConvert方法，然后去做你的逻辑吧。

**Comment by lozn00** [comment]
或者你录制一个视频弄到优酷，我看看效果。
